### ISSUE TITLE
sqlite3 CLI throws "Runtime error: '?' without operand"

### ISSUE THREAD

**Issue by mikeschinkel** [nalgeon/sqlite#15]
`sqlite3` CLI throws  _"Runtime error: '?' without operand"_ when using `(i?)` in `WHERE`  class, but not in `regexp_replace()`, and it works in the `WHERE` clause when using the extension via my GoLand IDE.

## The Code
```sql
SELECT * FROM
  (SELECT 'Foo' AS f UNION SELECT 'foo' UNION SELECT 'FOO') x
WHERE f REGEXP '(?i)Foo'
```

## The Error
```
Error: stepping, '?' without operand (1)
```

## The Screenshot
![CleanShot 2024-01-29 at 09 52 57@2x](https://github.com/nalgeon/sqlite/assets/153285/50a05ee1-289a-4034-a3d8-afff79a6a97f)

**Comment by nalgeon** [comment]
You haven't loaded the extension, hence the error. See [How to Install an Extension](https://github.com/nalgeon/sqlean/blob/main/docs/install.md#install-command-line-interface).

**Comment by mikeschinkel** [comment]
@nalgeon — Not true, unless I misunderstand. 

I am using `REGEXP`, `regexp_replace()`, `regexp_capture()`, and `regexp_substr()` in numerous places in my script, and they are mostly working.

This is the code I use to load the extension at the top of my script:

```sql
-- Load REGEXP extension
SELECT load_extension(home_dir.value||'/.sqlpkg/nalgeon/sqlean/regexp.dylib')
FROM config AS home_dir
WHERE key='home_dir';
```

**Comment by mikeschinkel** [comment]
Let me also emphasize that I am **_not_** getting that error when I load the extension and run the query in my GoLand IDE but I **_am_** getting that error — on the same script, which includes the `load_extension()` just before I start using `REGEXP`.

That is another reason I am pretty sure I have it loaded, because it **_is_** working via my IDE but **_not_** via the `sqlite` build that I downloaded from this repo.

**Comment by nalgeon** [comment]
For the `regexp` statement to work in the CLI, you have to load it with `.load`, not `load_extension()`.

Alternatively, you can use the `regexp_like` function instead of the `regexp` statement - it works with `load_extension()`.

**Comment by mikeschinkel** [comment]
Thank you for the reply.

> _"For the regexp statement to work in the CLI, you have to load it with .load, not load_extension()."_

Well, I started my project trying `.load` but then moved to `load_extension()`. 

This is a chicken-and-egg problem, it seems, as the query console of my JetBrain's IDEs does not support `.load` and only supports `load_extension()`, but your CLI version requires using `.load`  and not `load_extension()`.  See screenshot.

<img width="809" alt="CleanShot 2024-01-31 at 08 18 54@2x" src="https://github.com/nalgeon/sqlite/assets/153285/1c91b7b2-534d-45fe-a697-e2397a6250c4">

Since I am developing a set of scripts that are 1000+ queries, being able to work with the scripts interactively and being able to load a result window in a GUI — vs. doing it all via the `sqlite3` command line — is critical for me getting this project done is a reasonable amount of time. 

BTW, I also submitted [an issue regarding dot commands](https://youtrack.jetbrains.com/issue/DBE-19874/Query-Console-does-not-recognize-Sqlite-dot-commands) on JetBrain's bug tracker.

> _"Alternatively, you can use the regexp_like function instead of the regexp statement - it works with load_extension()."_

Yes, thank you for that suggestion, and I had already moved to doing exactly that as a workaround. 

Still, it is less than ideal for me _(and possibly for others.)_. For me it adds visual noise and complexity to writing the script — something I can deal with even though I wish were different — but for others they may end up repeating the time I wasted discovering the problem, and then finding a solution/workaround. Or possibly assume your extension does not work and just give up on it.

Yes, you can say _"works as intended"_ and as a fellow open-source developer I can acknowledge and accept that.

OTOH, from a developer experience perspective, not enabling the `sqlean` extension to be loading and work fully in your `sqlite3` build when loading using `load_extension()` is less than ideal.  

Fix this, or not _(assuming no technical reason bars you fixing it)_; either way I will respect whatever decision you make.

**Comment by nalgeon** [comment]
> not enabling the sqlean extension to be loading and work fully in your sqlite3 build when loading using load_extension() is less than ideal.

It's not something that I do or don't do. It's just the way SQLite CLI works as far as I understand it. Unfortunately, I don't have the capacity to investigate why it doesn't allow overriding the default `regexp` statement with `load_extension`.

**Comment by mikeschinkel** [comment]
> _Unfortunately, I don't have the capacity to investigate why it doesn't allow overriding the default `regexp` statement with `load_extension`._

Okay, thanks for the quick reply.

Very fair point.  Then it is what it is. 🤷
