### ISSUE TITLE
New 3.35.2 builds

### ISSUE THREAD

**Issue by jungle-boogie** [nalgeon/sqlite#2]
Hi,

Do you plan to build SQLite 3.35.2, which was released on the 17th?
https://www.sqlite.org/releaselog/3_35_2.html

Thanks for making the 64 bit builds! Keep up the good work with the blog posts as well.

Best!

**Comment by nalgeon** [comment]
Sure! There is [3.35.3](https://github.com/nalgeon/sqlite/releases/tag/3.35.3) already. I guess all those features in 3.35 made it a bit buggy ツ Thank you for reading the blog 👍

**Comment by jungle-boogie** [comment]
Oh, wow. Good thing you waited!
Thanks for the latest release.

**Comment by jungle-boogie** [comment]
Another release of SQLite has happened!

https://www.sqlite.org/releaselog/3_35_5.html

**Comment by nalgeon** [comment]
Wow, this is the first 5th patch release in the history of SQLite. It never took more than four before.
Built and published: [3.35.5](https://github.com/nalgeon/sqlite/releases/tag/3.35.5)

**Comment by jungle-boogie** [comment]
Thank you for the new builds! 

Yes, I'm sure drh and his team are ready to be finished with 3.35.x.  :)
