### ISSUE TITLE
Enable DSQLITE_ENABLE_MATH_FUNCTIONS

### ISSUE THREAD

**Issue by jungle-boogie** [nalgeon/sqlite#3]
Hi,

SQLite 3.35.0 added in math functions, but this is available as a compile time option only.
Would it be possible for you to consider enabling the compile time option for the extra features?

Here's the text to the compile time option:
https://www.sqlite.org/compile.html#enable_math_functions

BTW, it looks like there will be a fourth patch release for SQLite, 3.35.4, coming soon.

Thanks!

**Comment by nalgeon** [comment]
Sure! Compiled [3.35.4](https://github.com/nalgeon/sqlite/releases/tag/3.35.4) with math functions.
