### ISSUE TITLE
SQLite Archive Files support

### ISSUE THREAD

**Issue by magicprinc** [nalgeon/sqlite#4]
An original x86 version of SQLite3 shell from its official site contains "SQLite Archive Files" support:
https://www.sqlite.org/sqlar.html
It means two SQL functions (sqlar_compress/sqlar_uncompress) and command line API to manage such archives:
http://sqlite.org/cli.html#sqlite_archive_support

Could you please add it to your 64bit version?
I suppose it should be quite easy:
"Applications that already use SQLite for other purposes can easily add support for SQLite Archives using a small extension (https://sqlite.org/src/file/ext/misc/sqlar.c) to handle the compression and decompression of content."

**Comment by nalgeon** [comment]
SQLite Archive Files support requires `zlib`. AFAIK it is not available on Windows. I tried but failed to compile SQLite with zlib options, so currently I don' know how to support SQLite archives on Windows.

**Comment by nalgeon** [comment]
I've got no new ideas, going to close the issue.
