### ISSUE TITLE
Unicode text do not work in Windows console

### ISSUE THREAD

**Issue by valsor** [nalgeon/sqlite#5]
First thank you for your efforts building sqlite shell binaries.
Unfortunately I cannot make it work with Cyrillic text input/output in console. When I try to insert unicode text with INSERT statement sqlite3 hangs. The same behavior occurs with the official sqlite3.exe from sqlite.org. This is why I searched for alternative build and found your repo.
I'm on american Windows 10 19042 with Russian locale. I've tried it with no results in cmd.exe, PowerShell and the new Windows Terminal. Important to mention that other console apps as psql or git work with unicode input/output in the same environment without problems.
Do you have any idea why this occurs and what can be done to fix it? Thank you.

**Comment by nalgeon** [comment]
This has nothing to do with extensions, I'm afraid.

**Comment by valsor** [comment]
OK, I see. It seems there is some problem with shell itself. When I insert unicode text via GUI like SQLite Studio everything works as expected.
Do you know how to make it work?

**Comment by nalgeon** [comment]
Have you tried [setting the locale to UTF-8](https://stackoverflow.com/a/57134096)? Or maybe creating a UTF-8 text file with INSERTs and executing it against the CLI? Or using a database GUI like DBeaver?

**Comment by nalgeon** [comment]
I guess we'll never know.
